version: '3.8'
services:
  # db for main application (backend)
  maria-db:
    image: mariadb:10.11
    container_name: maria-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6B3D6E268DCB76E175A7DB3D9E031349AB2C32654C7E57581A851E64DD6214AB
      MYSQL_DATABASE: urc
      MYSQL_USER: root
      MYSQL_PASSWORD: 6B3D6E268DCB76E175A7DB3D9E031349AB2C32654C7E57581A851E64DD6214AB
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

  # phpMyAdmin just to check db connection (remove if needed)
  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "3081:80"
    depends_on:
      - maria-db
    environment:
      PMA_HOST: maria-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 6B3D6E268DCB76E175A7DB3D9E031349AB2C32654C7E57581A851E64DD6214AB

  # main back application container
  java-backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile
    container_name: java-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria-db

volumes:
  dbdata:
